name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install Dependencies
      run: dotnet restore

    - name: Update Event Key
      uses: deef0000dragon1/json-edit-action/@v1
      env:
        KEY: EventsDiscordWebHookURL
        VALUE: ${{ secrets.DISCORDEVENT }}
        FILE: keys.json

    - name: Update Channel Key
      uses: deef0000dragon1/json-edit-action/@v1
      env:
        KEY: ChannelDiscordWebHookURL
        VALUE: ${{ secrets.DISCORDEVENT }}
        FILE: keys.json

    - name: Build
      run: dotnet build --no-restore --verbosity normal

    - name: Test
      run: dotnet test --configuration Release --no-restore

    - name: DotNet Publish
      run: dotnet publish ArchaicQuestII.API/ArchaicQuestII.API.csproj -c Release -o deploy --self-contained true -r linux-x64

    - name: Copy via SSH
      uses: garygrossgarten/github-action-scp@v0.5.3
      with:
        local: deploy
        remote: ${{ secrets.REMOTE_TARGET }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_KEY }}

    - name: Run SSH Command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo systemctl restart archaicquest_api.service
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_KEY }}
